export interface CountryData {
  code: string;
  name: string;
  maleLE: number;
  femaleLE: number;
}

export const COUNTRIES: CountryData[] = [
  { code: 'JP', name: 'Japan', maleLE: 81, femaleLE: 87 },
  { code: 'CH', name: 'Switzerland', maleLE: 82, femaleLE: 86 },
  { code: 'AU', name: 'Australia', maleLE: 81, femaleLE: 85 },
  { code: 'ES', name: 'Spain', maleLE: 80, femaleLE: 86 },
  { code: 'IT', name: 'Italy', maleLE: 80, femaleLE: 85 },
  { code: 'SE', name: 'Sweden', maleLE: 81, femaleLE: 85 },
  { code: 'NO', name: 'Norway', maleLE: 81, femaleLE: 84 },
  { code: 'IS', name: 'Iceland', maleLE: 81, femaleLE: 84 },
  { code: 'FR', name: 'France', maleLE: 79, femaleLE: 85 },
  { code: 'NZ', name: 'New Zealand', maleLE: 80, femaleLE: 84 },
  { code: 'CA', name: 'Canada', maleLE: 80, femaleLE: 84 },
  { code: 'IE', name: 'Ireland', maleLE: 80, femaleLE: 84 },
  { code: 'LU', name: 'Luxembourg', maleLE: 80, femaleLE: 84 },
  { code: 'NL', name: 'Netherlands', maleLE: 80, femaleLE: 83 },
  { code: 'AT', name: 'Austria', maleLE: 79, femaleLE: 84 },
  { code: 'FI', name: 'Finland', maleLE: 79, femaleLE: 84 },
  { code: 'BE', name: 'Belgium', maleLE: 79, femaleLE: 83 },
  { code: 'DE', name: 'Germany', maleLE: 79, femaleLE: 84 },
  { code: 'PT', name: 'Portugal', maleLE: 78, femaleLE: 84 },
  { code: 'GR', name: 'Greece', maleLE: 79, femaleLE: 84 },
  { code: 'IL', name: 'Israel', maleLE: 81, femaleLE: 84 },
  { code: 'SG', name: 'Singapore', maleLE: 81, femaleLE: 86 },
  { code: 'KR', name: 'South Korea', maleLE: 80, femaleLE: 86 },
  { code: 'GB', name: 'United Kingdom', maleLE: 79, femaleLE: 83 },
  { code: 'DK', name: 'Denmark', maleLE: 79, femaleLE: 83 },
  { code: 'US', name: 'United States', maleLE: 76, femaleLE: 81 },
  { code: 'CZ', name: 'Czech Republic', maleLE: 76, femaleLE: 81 },
  { code: 'PL', name: 'Poland', maleLE: 74, femaleLE: 82 },
  { code: 'SK', name: 'Slovakia', maleLE: 74, femaleLE: 81 },
  { code: 'HU', name: 'Hungary', maleLE: 73, femaleLE: 79 },
  { code: 'CN', name: 'China', maleLE: 75, femaleLE: 79 },
  { code: 'CU', name: 'Cuba', maleLE: 77, femaleLE: 81 },
  { code: 'CL', name: 'Chile', maleLE: 78, femaleLE: 83 },
  { code: 'CR', name: 'Costa Rica', maleLE: 77, femaleLE: 82 },
  { code: 'AR', name: 'Argentina', maleLE: 74, femaleLE: 80 },
  { code: 'BR', name: 'Brazil', maleLE: 72, femaleLE: 79 },
  { code: 'CO', name: 'Colombia', maleLE: 73, femaleLE: 79 },
  { code: 'PE', name: 'Peru', maleLE: 73, femaleLE: 78 },
  { code: 'MX', name: 'Mexico', maleLE: 71, femaleLE: 77 },
  { code: 'TH', name: 'Thailand', maleLE: 74, femaleLE: 80 },
  { code: 'VN', name: 'Vietnam', maleLE: 71, femaleLE: 79 },
  { code: 'PH', name: 'Philippines', maleLE: 67, femaleLE: 75 },
  { code: 'ID', name: 'Indonesia', maleLE: 69, femaleLE: 73 },
  { code: 'MY', name: 'Malaysia', maleLE: 73, femaleLE: 77 },
  { code: 'TR', name: 'Turkey', maleLE: 75, femaleLE: 80 },
  { code: 'SA', name: 'Saudi Arabia', maleLE: 75, femaleLE: 78 },
  { code: 'AE', name: 'UAE', maleLE: 77, femaleLE: 79 },
  { code: 'EG', name: 'Egypt', maleLE: 70, femaleLE: 74 },
  { code: 'MA', name: 'Morocco', maleLE: 74, femaleLE: 77 },
  { code: 'TN', name: 'Tunisia', maleLE: 74, femaleLE: 77 },
  { code: 'ZA', name: 'South Africa', maleLE: 61, femaleLE: 68 },
  { code: 'GH', name: 'Ghana', maleLE: 63, femaleLE: 67 },
  { code: 'KE', name: 'Kenya', maleLE: 64, femaleLE: 69 },
  { code: 'ET', name: 'Ethiopia', maleLE: 64, femaleLE: 68 },
  { code: 'NG', name: 'Nigeria', maleLE: 62, femaleLE: 64 },
  { code: 'IN', name: 'India', maleLE: 68, femaleLE: 71 },
  { code: 'PK', name: 'Pakistan', maleLE: 65, femaleLE: 67 },
  { code: 'BD', name: 'Bangladesh', maleLE: 71, femaleLE: 74 },
  { code: 'RU', name: 'Russia', maleLE: 68, femaleLE: 78 },
  { code: 'UA', name: 'Ukraine', maleLE: 67, femaleLE: 77 },
  { code: 'OTHER', name: 'Other', maleLE: 71, femaleLE: 75 },
];

export function getCountryByCode(code: string): CountryData | undefined {
  return COUNTRIES.find((c) => c.code === code);
}
